### ISSUE TITLE
Sample data?

### ISSUE THREAD

**Issue by jsumners** [pitkley/dockerfiles#2]
I want to use this as a way to do some unit testing for a couple modules I maintain. How can I import sample data (users) into it automatically? Can I just point it to a json or yaml file with the data?

**Comment by pitkley** [comment]
Unfortunately I don't know which Dockerfile/image you are talking about since this repository contains multiple, could you please clarify? Thanks!

**Comment by jsumners** [comment]
Sorry, I wasn't paying attention. I am referring to https://github.com/pitkley/dockerfiles/tree/a8669b26d60b4a8b7e20e72ed16f9a0bfb42c316/samba-ad-dc

**Comment by pitkley** [comment]
Ah, no worries. In its current form it doesn't support the import of user data just by pointing it at a configuration file. Unfortunately I haven't used or maintained the Samba-AD-DC image in a very long time, since I'm not personally using it anymore, so I can't really tell you how this could work.

Some pointers though:

1. Take a look at [`samba_setup.sh`](https://github.com/pitkley/dockerfiles/blob/a8669b26d60b4a8b7e20e72ed16f9a0bfb42c316/samba-ad-dc/samba_setup.sh), specifically the [`samba domain provision` call](https://github.com/pitkley/dockerfiles/blob/a8669b26d60b4a8b7e20e72ed16f9a0bfb42c316/samba-ad-dc/samba_setup.sh#L34-L41). Maybe you can modify the setup-script at/after that point to load some data.
2. In general, when you run the image you should be able to supply an additional `samba` command either directly through `docker run` (as in `docker run ... pitkley/samba-ad-dc samba your-specific-commands`) or by executing in the running container using `docker exec` (both of which you could script and thus automate).

I hope this helps you. If you come up with a solution, I'd love for it to be documented here such that somebody else with the same goals can benefit. And if you modify the `Dockerfile` or surrounding scripts, feel free to send a PR!

**Comment by jsumners** [comment]
Okay, thanks. I'll look into if I manage to find the time. But I was unable to even find any documentation about seeding a SAMBA AD-DC with data, which is what led me to ask.

**Comment by VDGSecurity** [comment]
@jsumners I am looking for exactly the same thing. Did you come up with a solution to run AD in a docker container with some users added to the setup?

**Comment by jsumners** [comment]
I did not.

**Comment by VDGSecurity** [comment]
Thanks for the quick reply
